name: build release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Use Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: install dependencies
        run: npm ci && sudo apt-get install -y rpm jq
      - name: version
        run: echo "BINGSU_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV
        id: version

      - name: build app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
